// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9fatoBZYNIJ13II_qnqtkT7qX64aGUbQ',
    appId: '1:150500993673:web:9bd657f6999b1337717458',
    messagingSenderId: '150500993673',
    projectId: 'plants-a68ae',
    authDomain: 'plants-a68ae.firebaseapp.com',
    storageBucket: 'plants-a68ae.firebasestorage.app',
    measurementId: 'G-W38ZFR7T86',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8SeFeOtdP7SYafEjKu_vzVR6dx9RMb7Y',
    appId: '1:150500993673:android:3ff428a2361b8ad8717458',
    messagingSenderId: '150500993673',
    projectId: 'plants-a68ae',
    storageBucket: 'plants-a68ae.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjnbebl8Twcy-O05Aw41Ew24ezOLlOR3s',
    appId: '1:150500993673:ios:0956bf462e8d90ce717458',
    messagingSenderId: '150500993673',
    projectId: 'plants-a68ae',
    storageBucket: 'plants-a68ae.firebasestorage.app',
    androidClientId: '150500993673-0ijnq1u2s9ku79clq78hsq1kfi31t5hn.apps.googleusercontent.com',
    iosClientId: '150500993673-uappnsvk0vo1ki0t2q2b3tdlcmg347j0.apps.googleusercontent.com',
    iosBundleId: 'com.example.appPlants',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjnbebl8Twcy-O05Aw41Ew24ezOLlOR3s',
    appId: '1:150500993673:ios:0956bf462e8d90ce717458',
    messagingSenderId: '150500993673',
    projectId: 'plants-a68ae',
    storageBucket: 'plants-a68ae.firebasestorage.app',
    androidClientId: '150500993673-0ijnq1u2s9ku79clq78hsq1kfi31t5hn.apps.googleusercontent.com',
    iosClientId: '150500993673-uappnsvk0vo1ki0t2q2b3tdlcmg347j0.apps.googleusercontent.com',
    iosBundleId: 'com.example.appPlants',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA9fatoBZYNIJ13II_qnqtkT7qX64aGUbQ',
    appId: '1:150500993673:web:aed08e8fd341b935717458',
    messagingSenderId: '150500993673',
    projectId: 'plants-a68ae',
    authDomain: 'plants-a68ae.firebaseapp.com',
    storageBucket: 'plants-a68ae.firebasestorage.app',
    measurementId: 'G-H778GTYE3G',
  );
}
